### PR TITLE
fix regenerating .mozconfig.mk

### PR DESCRIPTION
**Pull request by roytam1**

### CODE REVIEW

**Comment by rn10950** [comment]
Looks good. If you don't mind me asking, what issue did this fix exactly? IIRC, the Mozilla subdirectory was only used in the official c-c trees. 

On a related note, I cloned your TLS branch and am building it on my Win2k build machine as we speak. I have never got your zip files to build, but that was probably due to some issue I did not catch, so your tree should build fine. If it does, would you be interested in submitting a pull request for that tree to the main branch? Would you be interested in collaborating on the project? I have a lot of free time now, so I will be working on RZ a lot more now. I think that if we both work together on this, we could create a really good browser, and possibly get more contributors as time goes on. We could aim for FF3 parity by September maybe, while also working on a frontend extension to mitigate some display issues for sites that target features that were introduced recently. 

I am new to Git, so until now, I was primarily working on the master branch. I will start working on feature branches, hopefully to make the master branch more stable to support contributions.

**Comment by roytam1** [comment]
> Looks good. If you don't mind me asking, what issue did this fix exactly? IIRC, the Mozilla subdirectory was only used in the official c-c trees.

This fixes generating .mozconfig.mk and other build-related issues including output obj folder and etc.

> If it does, would you be interested in submitting a pull request for that tree to the main branch?

yeah, we can do this one by one. I created new PR for that, before landing TLS 1.2 to main:
https://github.com/rn10950/RetroZilla/pull/16

**Comment by roytam1** [comment]
> We could aim for FF3 parity by September maybe

maybe incorporating Classilla's javascript engine? They ported Firefox 3.0's javascript engine into theirs.
but they did the changes on `#ifndef MOZILLA_1_8_BRANCH` which makes porting become harder.
branch is here: https://github.com/roytam1/classilla/tree/fix

**Comment by rn10950** [comment]
> yeah, we can do this one by one. I created new PR for that, before landing TLS 1.2 to main:

I got your TLS branch to build, so it's OK to merge in. If the TLS update was merged into the SQlite PR, then it's already in. If not, I'll go and merge it in.

Regarding the Classilla JS engine, I will look into it further. It seems promising. What version of Gecko was the latest Clasilla based on? I don't have access to a classic Mac or a reliable emulator to mess around with it often.

**Comment by roytam1** [comment]
> What version of Gecko was the latest Clasilla based on?

Mozilla suite 1.3.1, equivalent browser is phoenix-0.5.
It is way older that RetroZilla's rv version(1.8.1)
My phoenix branch is able to build under Windows like RetroZilla.
https://github.com/roytam1/classilla/tree/phoenix

**Comment by rn10950** [comment]
JS engine from Fx3: #18

**Pull request merged**
